services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www # Share code with Nginx for static file serving
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      target: development # Stops at the 'development' stage in Dockerfile
    container_name: laravel
    volumes:
      - ./backend:/var/www # Syncs your local PHP code
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=local

  frontend:
    build:
      context: ./frontend
      # This 'target' matches the 'AS development' stage in your Dockerfile
      target: development 
    container_name: nuxt
    working_dir: /app
    volumes:
      - ./frontend:/app
      - nodemodules:/app/node_modules # Named volume
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKID_USEPOLLING=true # Essential for hot-reload on some systems
    #ports:
     # - "3000:3000"
volumes:
  nodemodules: